server:
  port: 8083


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 25 # ?? connection ?
      max-lifetime: 25000 # 25?, ???? ??? ???? ???? ?? ??(???), DB wait_timeout(28.3?) ?? ?? ??
      idle-timeout: 30000 # 30?, ???? ?? ?? ??? ??? ? ?? ?? ??(???)
    #      housekeeping-period: 30000 # 30?, ??? ?? ???? ???? ???? ?? ???? ???? ??(???)

  jpa:
    open-in-view: false # controller ?? ????? ??? ? false? ??
    hibernate:
      ddl-auto: update # ??? ?? ? ???? ?? (create, create-drop, update, validate, none)
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # ????? SQL ??
        use_sql_comments: true # ?? JPQL SQL ?? ??

logging:
  level:
#    org.springframework.security.web: trace
    org.hibernate.SQL: debug # Hibernate? SQL? ??
    org.hibernate.orm.jdbc.bind: trace # Hibernate? SQL ???? ??
    org.springframework.transaction.interceptor: trace # Hibernate? SQL ???? ??


jwt:
  secret-key: 1234567890123456789012345678901234567890123456789012345678901234
  access-token-expiration-period: 5   # 5분
  refresh-token-expiration-period: 1440  # 24시간 60 * 24 = 1440분